dotnet add package Atlassian.SDK
dotnet add package Avalonia
dotnet add package Avalonia.Desktop
dotnet add package Avalonia.Direct2D1
dotnet add package Avalonia.FreeDesktop
dotnet add package Avalonia.Native
dotnet add package Avalonia.ReactiveUI
dotnet add package Avalonia.Remote.Protocol
dotnet add package Avalonia.Skia
dotnet add package Avalonia.Win32
dotnet add package Avalonia.X11
dotnet add package MessageBox.Avalonia
dotnet add package System.Text.Json
