name: OSX Build

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish Sikor.csproj --configuration OSX --framework netcoreapp3.1 --self-contained true --runtime osx-x64 /p:PublishSingleFile=true --output out
    - name: Test
      run: chmod +x out/Sikor && out/Sikor --run-test && chmod +x posix-pack-test.sh && ./posix-pack-test.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/Sikor
        tag: ${{ github.ref }}
        asset_name: Sikor-OSX-x64
        overwrite: true
        file_glob: false
