name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish Sikor.csproj --configuration Windows --framework netcoreapp3.1 --self-contained true --runtime win-x64 /p:PublishSingleFile=true --output out
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/Sikor
        tag: ${{ github.ref }}
        asset_name: Sikor-Win-x64
        overwrite: true
        file_glob: false
